# Generated by Django 3.2.18 on 2023-04-23 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_auto_20230423_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='customer',
            new_name='user',
        ),
    ]
